/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.swig.jni;

public class RecordStreamJNI {
  public final static native void stopFlag_set(int jarg1);
  public final static native int stopFlag_get();
  public final static native int start(String jarg1, String jarg2);
  public final static native int stop();
}
