package com.example.client.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.client.greendao.Cat;
import com.example.client.greendao.Dog;
import com.example.client.greendao.JoinUserWithSheep;
import com.example.client.greendao.Sheep;
import com.example.client.greendao.User;

import com.example.client.dao.CatDao;
import com.example.client.dao.DogDao;
import com.example.client.dao.JoinUserWithSheepDao;
import com.example.client.dao.SheepDao;
import com.example.client.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig catDaoConfig;
    private final DaoConfig dogDaoConfig;
    private final DaoConfig joinUserWithSheepDaoConfig;
    private final DaoConfig sheepDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CatDao catDao;
    private final DogDao dogDao;
    private final JoinUserWithSheepDao joinUserWithSheepDao;
    private final SheepDao sheepDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        catDaoConfig = daoConfigMap.get(CatDao.class).clone();
        catDaoConfig.initIdentityScope(type);

        dogDaoConfig = daoConfigMap.get(DogDao.class).clone();
        dogDaoConfig.initIdentityScope(type);

        joinUserWithSheepDaoConfig = daoConfigMap.get(JoinUserWithSheepDao.class).clone();
        joinUserWithSheepDaoConfig.initIdentityScope(type);

        sheepDaoConfig = daoConfigMap.get(SheepDao.class).clone();
        sheepDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        catDao = new CatDao(catDaoConfig, this);
        dogDao = new DogDao(dogDaoConfig, this);
        joinUserWithSheepDao = new JoinUserWithSheepDao(joinUserWithSheepDaoConfig, this);
        sheepDao = new SheepDao(sheepDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Cat.class, catDao);
        registerDao(Dog.class, dogDao);
        registerDao(JoinUserWithSheep.class, joinUserWithSheepDao);
        registerDao(Sheep.class, sheepDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        catDaoConfig.clearIdentityScope();
        dogDaoConfig.clearIdentityScope();
        joinUserWithSheepDaoConfig.clearIdentityScope();
        sheepDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CatDao getCatDao() {
        return catDao;
    }

    public DogDao getDogDao() {
        return dogDao;
    }

    public JoinUserWithSheepDao getJoinUserWithSheepDao() {
        return joinUserWithSheepDao;
    }

    public SheepDao getSheepDao() {
        return sheepDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
