package com.example.client.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.client.greendao.JoinUserWithSheep;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOIN_USER_WITH_SHEEP".
*/
public class JoinUserWithSheepDao extends AbstractDao<JoinUserWithSheep, Long> {

    public static final String TABLENAME = "JOIN_USER_WITH_SHEEP";

    /**
     * Properties of entity JoinUserWithSheep.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UId = new Property(1, Long.class, "uId", false, "U_ID");
        public final static Property SId = new Property(2, Long.class, "sId", false, "S_ID");
    }


    public JoinUserWithSheepDao(DaoConfig config) {
        super(config);
    }
    
    public JoinUserWithSheepDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOIN_USER_WITH_SHEEP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"U_ID\" INTEGER," + // 1: uId
                "\"S_ID\" INTEGER);"); // 2: sId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOIN_USER_WITH_SHEEP\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JoinUserWithSheep entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long uId = entity.getUId();
        if (uId != null) {
            stmt.bindLong(2, uId);
        }
 
        Long sId = entity.getSId();
        if (sId != null) {
            stmt.bindLong(3, sId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JoinUserWithSheep entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long uId = entity.getUId();
        if (uId != null) {
            stmt.bindLong(2, uId);
        }
 
        Long sId = entity.getSId();
        if (sId != null) {
            stmt.bindLong(3, sId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JoinUserWithSheep readEntity(Cursor cursor, int offset) {
        JoinUserWithSheep entity = new JoinUserWithSheep( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // uId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // sId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JoinUserWithSheep entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setSId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JoinUserWithSheep entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JoinUserWithSheep entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JoinUserWithSheep entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
