/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.swig.jni;

public class GCD {
  public static int gcd(int x, int y) {
    return GCDJNI.gcd(x, y);
  }

}
