/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.service.jni;

public class record {
  public static void setStopFlag(int value) {
    recordJNI.stopFlag_set(value);
  }

  public static int getStopFlag() {
    return recordJNI.stopFlag_get();
  }

  public static int start(String input, String output) {
    return recordJNI.start(input, output);
  }

  public static int stop() {
    return recordJNI.stop();
  }

}
