/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_evideo_service_manager_RecordManager */

#ifndef _Included_com_evideo_service_manager_RecordManager
#define _Included_com_evideo_service_manager_RecordManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_evideo_service_manager_RecordManager
 * Method:    native_start
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_evideo_service_manager_RecordManager_native_1start
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_evideo_service_manager_RecordManager
 * Method:    native_stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_evideo_service_manager_RecordManager_native_1stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
